services:
  migrator:
    build:
      context: ../
      dockerfile: ./bun-budget-api/Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/budget_api
    command: bunx prisma migrate deploy
    depends_on:
      postgres:
        condition: service_healthy

  server:
    build:
      context: ../
      dockerfile: ./bun-budget-api/Dockerfile.prod
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://user:password@postgres/budget_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.0" # Limit to 2 CPU cores
          memory: "1G" # Limit to 1 GB of RAM

  postgres:
    image: postgres:10.3
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2.0" # Limit to 2 CPU cores
          memory: "1G" # Limit to 1 GB of RAM
