FROM oven/bun

WORKDIR /usr/src/app

COPY ./bun-budget-api/package.json ./bun-budget-api/bun.lockb ./

COPY ./docs/openapi.yaml .

RUN bun install --frozen-lockfile

COPY ./bun-budget-api .

RUN bunx prisma generate

CMD bun run dev
