services:
  k6:
    image: grafana/k6
    command: run /functional-tests.js
    volumes:
      - ./functional-tests.js:/functional-tests.js
      - ./helpers.js:/helpers.js
    network_mode: "host"
    environment:
      - BASE_URL=http://localhost:8080
