services:
  influxdb:
    image: influxdb:1.8 # Version 2.x introduces some breaking compatibility changes. K6 support for it comes via an extension
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    command: run /load-tests.js
    volumes:
      - ./load-tests.js:/load-tests.js
      - ./helpers.js:/helpers.js
    network_mode: "host"
    environment:
      - BASE_URL=http://localhost:8080
      - K6_OUT=influxdb=http://localhost:8086/k6
