services:
  k6:
    image: grafana/k6:latest
    command: run /load-tests.js
    volumes:
      - ./load-tests.js:/load-tests.js
      - ./helpers.js:/helpers.js
      - ./results:/results
    network_mode: host
    environment:
      - BASE_URL=http://localhost:8080
      - K6_OUT=influxdb=http://localhost:8086/k6
    deploy:
      resources:
        limits:
          cpus: "1.0" # Limit to 1 CPU core
          memory: "1G" # Limit to 1 GB of RAM
