services:
  k6:
    image: grafana/k6:latest
    command: run /load-tests-light.js
    volumes:
      - ./load-tests-light.js:/load-tests-light.js
      - ./helpers.js:/helpers.js
      - ./results:/results
    environment:
      - BASE_URL=http://server:8080
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - budget-api
      - influxdb-grafana
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

networks:
  budget-api:
    external: true
    name: budget-api
  influxdb-grafana:
    external: true
    name: influxdb-grafana
