services:
  server:
    build:
      context: ../
      dockerfile: ./node-budget-api/Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://user:password@postgres/budget_api
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  postgres:
    image: postgres:10.3
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

networks:
  default:
    name: budget-api
