services:
  influxdb:
    image: influxdb:1.8 # Version 2.x introduces some breaking compatibility changes. K6 support for it comes via an extension
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./data/grafana:/etc/grafana/provisioning/
    network_mode: host
