services:
  server:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_api
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8081:8080
