services:
  docker-stats-recorder:
    build: .
    restart: unless-stopped
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_DB: k6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: influxdb-grafana
