[package]
name = "rust-budget-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
tower-http = { version = "=0.6.1", features = ["fs"] }
