services:
  server:
    build:
      context: ../
      dockerfile: ./rust-budget-api/Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://user:password@postgres/budget_api
  postgres:
    image: postgres:10.3
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - 8081:8080
