FROM rust:1.82.0

WORKDIR /usr/src/app

# Install binstall for binary installations
# Otherwise would have to compile the binaries every time
# Installing with curl instead of cargo install to also avoid the need to compile cargo-binstall
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# Install live reload tool
RUN cargo binstall cargo-watch

# Install database ORM cli tool
RUN cargo binstall diesel_cli

COPY rust-budget-api/ ./

COPY ./docs/openapi.yaml .

RUN cargo build

# Watch changes on source files and quietly execute cargo run on file changes
CMD ["cargo", "watch", "-q", "-x", "run"]
