version: "3"

tasks:
  run:
    cmds:
      - docker compose -f docker-compose.dev.yaml up --build
  run:database:
    cmds:
      - docker compose -f docker-compose.dev.yaml up postgres adminer
  lint:check:
    cmds:
      - cargo clippy
  lint:fix:
    cmds:
      - cargo clippy --fix
  format:check:
    cmds:
      - cargo fmt --check
  format:fix:
    cmds:
      - cargo fmt
  diesel:
    cmds:
      - docker run --rm --network="rust-budget-api_default" -v "$(pwd)":/app willsquire/diesel-cli {{.CLI_ARGS}}
  migration:run:
    cmds:
      - task diesel -- --database-url=postgresql://user:password@postgres/budget_api migration run
  migration:redo:
    cmds:
      - task diesel -- --database-url=postgresql://user:password@postgres/budget_api migration redo
  test:
    cmds:
      - cargo test
