name: CI Bun

on:
  push:
    branches:
      - main
    paths:
      - "bun-budget-api/**"
      - "k6/**"
      - "**/CI-bun.yaml"
      - "**/publish-docker-image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "bun-budget-api/**"
      - "k6/**"
      - "**/CI-bun.yaml"
      - "**/publish-docker-image.yaml"

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: ./bun-budget-api

      - name: Run linter
        run: bun run lint
        working-directory: ./bun-budget-api

      - name: Run unit tests
        run: bun test
        working-directory: ./bun-budget-api

      - name: Run full environment with docker compose
        run: docker compose up --wait
        working-directory: ./bun-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 API tests
        run: BASE_URL=http://localhost:8080 k6 run k6/api-tests.js

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      project_name: bun
      dockerfile_path: bun-budget-api/Dockerfile.prod
