name: CI C#

on:
  push:
    branches:
      - main
    paths:
      - "cs-budget-api/**"
      - "k6/**"
      - "**/CI-cs.yaml"
      - "**/publish-docker-image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "cs-budget-api/**"
      - "k6/**"
      - "**/CI-cs.yaml"
      - "**/publish-docker-image.yaml"

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Run formatter
        run: dotnet format main --verify-no-changes
        working-directory: ./cs-budget-api

      - name: Run build
        run: dotnet build main
        working-directory: ./cs-budget-api

      - name: Run unit tests
        run: dotnet test test
        working-directory: ./cs-budget-api

      - name: Run full environment with docker compose
        run: docker compose up --wait
        working-directory: ./cs-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 API tests
        run: BASE_URL=http://localhost:8080 k6 run k6/api-tests.js

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      project_tag: cs
      dockerfile_path: cs-budget-api/Dockerfile.prod
