name: CI Go

on:
  push:
    branches:
      - main
    paths:
      - 'go-budget-api/**'
      - '**/CI-go.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'go-budget-api/**'
      - '**/CI-go.yaml'

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: go-budget-api

      - name: Run unit tests
        run: go test -v ./...
        working-directory: ./go-budget-api

      # - name: Run full environment with docker compose
      #   run: docker compose -f docker-compose.dev.yaml up --wait
      #   working-directory: ./go-budget-api

      # - name: Setup K6
      #   uses: grafana/setup-k6-action@v1

      # - name: Run K6 API tests
      #   run: BASE_URL=http://localhost:8080 k6 run k6/api-tests.js
