name: CI Go

on:
  push:
    branches:
      - main
    paths:
      - 'go-budget-api/**'
      - '**/CI-go.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'go-budget-api/**'
      - '**/CI-go.yaml'

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
