name: CI Go

on:
  push:
    branches:
      - main
    paths:
      - "go-budget-api/**"
      - "k6/**"
      - "**/CI-go.yaml"
      - "**/publish-docker-image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "go-budget-api/**"
      - "k6/**"
      - "**/CI-go.yaml"
      - "**/publish-docker-image.yaml"

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: go-budget-api

      - name: Run unit tests
        run: go test -v ./...
        working-directory: ./go-budget-api

      - name: Run full environment with docker compose
        run: docker compose up --wait
        working-directory: ./go-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 API tests
        run: BASE_URL=http://localhost:8080 k6 run k6/functional-tests.js

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      project_tag: go
      dockerfile_path: go-budget-api/Dockerfile.prod
