name: CI Node

on:
  push:
    branches:
      - main
    paths:
      - "node-budget-api/**"
      - "k6/**"
      - "**/CI-node.yaml"
      - "**/publish-docker-image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "node-budget-api/**"
      - "k6/**"
      - "**/CI-node.yaml"
      - "**/publish-docker-image.yaml"

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ./node-budget-api

      - name: Run linter
        run: npm run lint
        working-directory: ./node-budget-api

      - name: Run unit tests
        run: npm test
        working-directory: ./node-budget-api

      - name: Run full environment with docker compose
        run: docker compose up --wait
        working-directory: ./node-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 API tests
        run: BASE_URL=http://localhost:8080 k6 run k6/api-tests.js

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      project_tag: node
      dockerfile_path: node-budget-api/Dockerfile
