name: CI Node

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-20.04

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    defaults:
      run:
        working-directory: ./node-budget-api

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ./node-budget-api

      - name: Run linter
        run: npm run lint
        working-directory: ./node-budget-api

      - name: Run unit tests
        run: npm test
        working-directory: ./node-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Start server for k6 testing
        run: npm start &
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          PORT: 8080
        working-directory: ./node-budget-api

      - name: Run K6 functional API tests
        uses: grafana/run-k6-action@v1
        with:
          path: "k6/api-tests.js"
        env:
          BASE_URL: http://localhost:8080

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          format: 'YYYYMMDDHHmmss'

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: node-budget-api/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:node
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:node-${{ steps.time.outputs.time }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:node-latest
          push: true
