name: CI Rust

on:
  push:
    branches:
      - main
    paths:
      - 'rust-budget-api/**'
      - 'k6/**'
      - '**/CI-rust.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'rust-budget-api/**'
      - 'k6/**'
      - '**/CI-rust.yaml'

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run linter
        run: task lint:check
        working-directory: ./rust-budget-api

      - name: Run Formatter
        run: task format:check
        working-directory: ./rust-budget-api
