name: CI Rust

on:
  push:
    branches:
      - main
    paths:
      - "rust-budget-api/**"
      - "k6/**"
      - "**/CI-rust.yaml"
      - "**/publish-docker-image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "rust-budget-api/**"
      - "k6/**"
      - "**/CI-rust.yaml"
      - "**/publish-docker-image.yaml"

jobs:
  verification:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run linter
        run: task lint:check
        working-directory: ./rust-budget-api

      - name: Run Formatter
        run: task format:check
        working-directory: ./rust-budget-api

      - name: Run unit tests
        run: task test
        working-directory: ./rust-budget-api

      - name: Run full environment with docker compose
        run: docker compose up --wait
        working-directory: ./rust-budget-api

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 API tests
        run: BASE_URL=http://localhost:8080 k6 run k6/api-tests.js

  publish_docker_image:
    needs: [verification]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      project_tag: rust
      dockerfile_path: rust-budget-api/Dockerfile.prod
