name: Publish Docker Image

on:
  workflow_call:
    inputs:
      project_tag:
        description: "Unique tag of the project"
        required: true
        type: string
      dockerfile_path:
        description: "Path to the Dockerfile"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish_docker_image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          format: "YYYYMMDDHHmmss"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          tags: |
            ${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.project_tag }}
            ${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.project_tag }}-${{ steps.time.outputs.time }}
            ${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.project_tag }}-latest
          push: true
