FROM golang:1.23.2 AS build-stage

WORKDIR /usr/src/app

COPY go-budget-api/ ./

RUN go mod download

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN go build cmd/main/main.go

FROM scratch

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/main .

COPY ./docs/openapi.yaml .

ENV GIN_MODE=release

CMD ["./main"]
