services:
  server:
    build:
      context: ../
      dockerfile: ./go-budget-api/Dockerfile.prod
    restart: unless-stopped
    environment:
      PORT: 8080
      CONNECTION_STRING: host=postgres user=user password=password dbname=budget_api sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      migrator:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2.0" # Limit to 2 CPU cores
          memory: "1G" # Limit to 1 GB of RAM

  migrator:
    build:
      context: ../
      dockerfile: ./go-budget-api/Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    command: atlas migrate apply --url "postgresql://user:password@postgres/budget_api?sslmode=disable"

  postgres:
    image: postgres:10.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2.0" # Limit to 2 CPU cores
          memory: "1G" # Limit to 1 GB of RAM
