version: '3'

tasks:
  run:
    cmds:
      - docker compose -f docker-compose.dev.yaml up --build
  run:database:
    cmds:
      - docker compose -f docker-compose.dev.yaml up postgres adminer
  lint:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.61.0 golangci-lint run {{.CLI_ARGS}}
  lint:fix:
    cmds:
      - task lint -- --fix
  migration:inspect:
    cmds:
      - atlas schema inspect --env gorm --url "env://src"
  migration:generate:
    cmds:
      - atlas migrate diff --env gorm
  migration:run:
    cmds:
      - atlas migrate apply --url "postgresql://user:password@postgres/budget_api"
