version: '3'

tasks:
  run:
    cmds:
      - docker compose -f docker-compose.dev.yaml up --build
  lint:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.61.0 golangci-lint run {{.CLI_ARGS}}
  lint:fix:
    cmds:
      - task lint -- --fix
